# Generated by Django 3.2 on 2021-04-23 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costumer_name', models.CharField(max_length=80, verbose_name='Name')),
                ('costumer_email', models.EmailField(max_length=120, verbose_name='Email')),
                ('costumer_mobile', models.CharField(max_length=40, verbose_name='Mobile')),
                ('status', models.CharField(default='CREATED', max_length=20, verbose_name='Status')),
                ('create_at', models.DateField(auto_now_add=True)),
                ('update_at', models.DateField(auto_now=True)),
            ],
        ),
    ]
