# Generated by Django 3.2 on 2021-04-23 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='process_url',
            field=models.CharField(default=4561, max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='request_id',
            field=models.CharField(default=2332, max_length=40),
            preserve_default=False,
        ),
    ]
